import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  clientPrefix: "NEXT_PUBLIC_",
  server: {
    DATABASE_URL: z.string().url(),
    NEXTAUTH_SECRET: z.string(),
    NEXTAUTH_URL: z.string().url(),
    DISCORD_CLIENT_ID: z.string(),
    DISCORD_CLIENT_SECRET: z.string(),
    GOOGLE_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    ABLY_API_KEY: z.string(),
    TWITTER_CLIENT_ID: z.string(),
    TWITTER_CLIENT_SECRET: z.string(),
    UPLOADCARE_SECRET_KEY: z.string(),
    ES_CERTIFICATE: z.string(),
    ES_API_KEY: z.string(),
    STRIPE_SECRET_KEY: z.string(),
    WEBHOOK_SECRET: z.string(),
    WEBHOOK_CONNECT_SECRET: z.string(),
    TWILIO_SID: z.string(),
    AUTH_TOKEN: z.string(),
    TWILIO_NUMBER: z.string(),
    MESSAGING_SID: z.string(),
    EMAIL_SERVER_PASSWORD: z.string(),
    EMAIL_FROM: z.string(),
    EMAIL_SERVER_USER: z.string(),
    EMAIL_SERVER_PORT: z.string(),
    EMAIL_SERVER_HOST: z.string(),
    PUSHER_SECRET: z.string(),
    TEST_ACCESS_PASSWORD: z.string(),
    CRON_TOKEN: z.string(),
    CLOUDFLARE_ACCESS_KEY: z.string(),
    CLOUDFLARE_ACCESS_SECRET: z.string(),
    CLOUDFLARE_ACCOUNT_ID: z.string(),
    CLERK_SECRET_KEY: z.string(),
    EXPO_ACCESS_TOKEN: z.string(),
    ABLY_HASH: z.string(),
    ALGOLIA_SECRET_KEY: z.string(),
    NODE_ENV: z.enum(["development", "test", "production"]),
  },
  client: {
    NEXT_PUBLIC_URL: z.string(),
    NEXT_PUBLIC_UPLOADCARE_PUB_KEY: z.string(),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string(),
    NEXT_PUBLIC_PUSHER_APP_ID: z.string(),
    NEXT_PUBLIC_PUSHER_KEY: z.string(),
    NEXT_PUBLIC_PUSHER_CLUSTER: z.string(),
    NEXT_PUBLIC_MIXPANEL_TOKEN: z.string(),
    NEXT_PUBLIC_IN_DEV: z.string(),
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string(),
    NEXT_PUBLIC_ALGOLIA_APP_ID: z.string(),
    NEXT_PUBLIC_ALGOLIA_API_KEY: z.string(),
    NEXT_PUBLIC_ALGOLIA_INDEX_NAME: z.string(),
  },
  /**
   * What object holds the environment variables at runtime.
   * Often `process.env` or `import.meta.env`
   */
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    NODE_ENV: process.env.NODE_ENV,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    EXPO_ACCESS_TOKEN: process.env.EXPO_ACCESS_TOKEN,
    ABLY_API_KEY: process.env.ABLY_API_KEY,
    ABLY_HASH: process.env.ABLY_HASH,
    NEXT_PUBLIC_ALGOLIA_APP_ID: process.env.NEXT_PUBLIC_ALGOLIA_APP_ID,
    NEXT_PUBLIC_ALGOLIA_API_KEY: process.env.NEXT_PUBLIC_ALGOLIA_API_KEY,
    NEXT_PUBLIC_ALGOLIA_INDEX_NAME: process.env.NEXT_PUBLIC_ALGOLIA_INDEX_NAME,
    ALGOLIA_SECRET_KEY: process.env.ALGOLIA_SECRET_KEY,
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
    NEXT_PUBLIC_UPLOADCARE_PUB_KEY: process.env.NEXT_PUBLIC_UPLOADCARE_PUB_KEY,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_PUSHER_APP_ID: process.env.NEXT_PUBLIC_PUSHER_APP_ID,
    NEXT_PUBLIC_PUSHER_KEY: process.env.NEXT_PUBLIC_PUSHER_KEY,
    NEXT_PUBLIC_PUSHER_CLUSTER: process.env.NEXT_PUBLIC_PUSHER_CLUSTER,
    NEXT_PUBLIC_MIXPANEL_TOKEN: process.env.NEXT_PUBLIC_MIXPANEL_TOKEN,
    NEXT_PUBLIC_IN_DEV: process.env.NEXT_PUBLIC_IN_DEV,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
    TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
    UPLOADCARE_SECRET_KEY: process.env.UPLOADCARE_SECRET_KEY,
    ES_CERTIFICATE: process.env.ES_CERTIFICATE,
    ES_API_KEY: process.env.ES_API_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    WEBHOOK_SECRET: process.env.WEBHOOK_SECRET,
    WEBHOOK_CONNECT_SECRET: process.env.WEBHOOK_CONNECT_SECRET,
    TWILIO_SID: process.env.TWILIO_SID,
    AUTH_TOKEN: process.env.AUTH_TOKEN,
    TWILIO_NUMBER: process.env.TWILIO_NUMBER,
    MESSAGING_SID: process.env.MESSAGING_SID,
    EMAIL_SERVER_PASSWORD: process.env.EMAIL_SERVER_PASSWORD,
    EMAIL_FROM: process.env.EMAIL_FROM,
    EMAIL_SERVER_USER: process.env.EMAIL_SERVER_USER,
    EMAIL_SERVER_PORT: process.env.EMAIL_SERVER_PORT,
    EMAIL_SERVER_HOST: process.env.EMAIL_SERVER_HOST,
    PUSHER_SECRET: process.env.PUSHER_SECRET,
    TEST_ACCESS_PASSWORD: process.env.TEST_ACCESS_PASSWORD,
    CRON_TOKEN: process.env.CRON_TOKEN,
    CLOUDFLARE_ACCESS_KEY: process.env.CLOUDFLARE_ACCESS_KEY,
    CLOUDFLARE_ACCESS_SECRET: process.env.CLOUDFLARE_ACCESS_SECRET,
    CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
  },
});
