name: hourly-cron
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://dev.sakpa.co/api/reminder' \
          --header 'Authorization: Bearer ${{ secrets.CRON_TOKEN }}'
